baseURL                = "https://willhou.pages.dev/"
languageCode           = "en"
title                  = "WillHou's Blog"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "en"
disableLanguages = ["zh", "ja", "zh-hant-tw"]

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = true

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
[services.googleAnalytics]
    id = "G-WRCE7VN12B"